name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install yarn dependencies
        run: yarn install

  test-app:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Run yarn test
        run: yarn test
