name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  install-and-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Instalar dependências
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Instalar dependências
        run: yarn install 
        
      - name: Instalar Cypress
        run: yarn add cypress@latest
        
      - name: Executar Cypress
        run: yarn test
        
  deploy-to-vercel:
    runs-on: ubuntu-latest
    needs: install-and-tests
    steps:
      - name: Install Vercel CLI
        run: yarn add vercel -g

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@19d4fbf5eb89beb6127a64278a7a835e1901f5b8
        with:
          vercel-token: 7CM0F9elSws7yeHkm3xlPPFy

          
