name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Instalar dependências
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Instalar dependências
        run: yarn install 

      - name: Build
        run: yarn build

  install-and-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Instalar dependências
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Instalar dependências
        run: yarn install 
        
      - name: Executar Tests
        run: yarn test

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Instalar dependências
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Instalar Vercel CLI
        run: npm install -g vercel
        
      - name: Vercel Pull
        run: vercel pull --yes --environment=production --token=7CM0F9elSws7yeHkm3xlPPFy

      - name: Vercel Build
        run: vercel build --prod --token=7CM0F9elSws7yeHkm3xlPPFy

      - name: Vercel Deploy
        run: vercel deploy --prebuilt --prod --token=7CM0F9elSws7yeHkm3xlPPFy

      
