name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  install-and-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Instalar dependências
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Instalar dependências
        run: yarn install 
        
      - name: Instalar Cypress
        run: yarn add cypress@latest
        
      - name: Executar Cypress
        run: yarn test
