name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Instalar dependências
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Instalar dependências
        run: yarn install 
        
      - name: Instalar Cypress
        run: yarn add cypress@latest
  test:
    runs-on: ubuntu-latest
    needs: [install]

    steps:
      - uses: actions/checkout@v2

      - name: Executar Cypress
        run: yarn test

  deploy:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - uses: actions/checkout@v2

      - name: Vercel Action
        # You may pin to the exact commit or the version.
        # uses: amondnet/vercel-action@19d4fbf5eb89beb6127a64278a7a835e1901f5b8
        uses: amondnet/vercel-action@v25
        with:
          # Vercel token
          vercel-token: 7CM0F9elSws7yeHkm3xlPPFy
          project-path: ./
